apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: postgresql
  repository: '@bitnami'
  version: 10.13.8
description: A Helm chart for Kubernetes
name: todo-chart
type: application
version: 0.1.0
